<?php

declare(strict_types=1);

namespace App;

class Scenarios
{
    /**
     * Circuits types proposés dans le builder et sur /circuits-types.
     * Catégories : Solo, Couple, Famille, Indépendant, Épargne, Collectif.
     */
    public static function all(): array
    {
        $node = static function (string $id, string $kind, string $title, float $x, float $y, float $amount = 0, array $extra = []): array {
            return array_merge(compact('id', 'kind', 'title', 'x', 'y', 'amount'), $extra);
        };
        $C = [
            'revenu' => 'oklch(0.62 0.12 192)',
            'compte' => 'oklch(0.32 0.09 265)',
            'repartiteur' => 'oklch(0.68 0.18 38)',
            'livret' => 'oklch(0.48 0.11 240)',
            'depense' => 'oklch(0.55 0.16 25)',
        ];
        $thumbs = [
            'solo' => [
                'wires' => ['M40 68 C80 68 80 42 120 42', 'M164 44 C200 44 200 24 240 24', 'M164 48 C200 48 200 96 240 96'],
                'dots' => [[8, 60, 32, $C['revenu']], [120, 34, 44, $C['compte']], [240, 16, 52, $C['depense']], [240, 88, 52, $C['livret']]],
            ],
            'two-in' => [
                'wires' => ['M40 30 C80 30 80 68 120 68', 'M40 104 C80 104 80 72 120 72', 'M164 70 C200 70 200 34 240 34', 'M164 74 C200 74 200 104 240 104'],
                'dots' => [[8, 22, 32, $C['revenu']], [8, 96, 32, $C['revenu']], [120, 60, 44, $C['compte']], [240, 26, 52, $C['depense']], [240, 96, 52, $C['livret']]],
            ],
            'pro' => [
                'wires' => ['M40 68 C80 68 80 30 120 30', 'M40 72 C80 72 80 104 120 104', 'M164 32 C200 32 210 68 240 68'],
                'dots' => [[8, 60, 32, $C['revenu']], [120, 22, 44, $C['compte']], [120, 96, 44, $C['depense']], [240, 60, 52, $C['livret']]],
            ],
            'save' => [
                'wires' => ['M40 68 C80 68 80 42 120 42', 'M164 44 C200 44 200 24 240 24', 'M164 48 C200 48 200 96 240 96'],
                'dots' => [[8, 60, 32, $C['revenu']], [120, 34, 44, $C['repartiteur']], [240, 16, 52, $C['livret']], [240, 88, 52, $C['livret']]],
            ],
            'goal' => [
                'wires' => ['M40 42 C80 42 80 68 120 68', 'M40 104 C80 104 80 72 120 72', 'M164 70 C210 70 210 42 240 42'],
                'dots' => [[8, 34, 32, $C['revenu']], [8, 96, 32, $C['revenu']], [120, 60, 44, $C['repartiteur']], [240, 34, 52, $C['livret']]],
            ],
            'family' => [
                'wires' => ['M40 28 C80 28 80 64 120 64', 'M40 100 C80 100 80 68 120 68', 'M164 66 C200 66 200 28 240 28', 'M164 70 C200 70 200 100 240 100'],
                'dots' => [[8, 20, 32, $C['revenu']], [8, 92, 32, $C['revenu']], [120, 56, 44, $C['repartiteur']], [240, 20, 52, $C['livret']], [240, 92, 52, $C['depense']]],
            ],
            'rental' => [
                'wires' => ['M40 68 C80 68 80 36 120 36', 'M164 38 C200 38 200 22 240 22', 'M164 42 C200 42 200 96 240 96'],
                'dots' => [[8, 60, 32, $C['revenu']], [120, 28, 44, $C['compte']], [240, 14, 52, $C['depense']], [240, 88, 52, $C['livret']]],
            ],
        ];

        return [
            'premier-salaire' => [
                'title' => 'Premier salaire',
                'category' => 'Solo',
                'hint' => 'Un salaire, les charges du mois, et 20 % versés à l’épargne avant le reste du quotidien.',
                'thumb' => $thumbs['solo'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire', 40, 40, 1900),
                        $node('c1', 'compte', 'Compte courant', 360, 40),
                        $node('dloyer', 'depense', 'Loyer', 720, 40),
                        $node('dcour', 'depense', 'Quotidien', 720, 200),
                        $node('p1', 'repartiteur', 'Épargne', 720, 360),
                        $node('lep', 'livret', 'LEP', 1040, 280, 0, ['rate' => 2.5, 'cap' => 10000, 'start' => 0, 'preset' => 'lep']),
                        $node('la', 'livret', 'Livret A', 1040, 440, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'dloyer', 'mode' => 'fixe', 'value' => 650],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'pct', 'value' => 20],
                        ['from' => 'c1', 'to' => 'dcour', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'lep', 'mode' => 'fixe', 'value' => 250],
                        ['from' => 'p1', 'to' => 'la', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'etudiant' => [
                'title' => 'Étudiant',
                'category' => 'Solo',
                'hint' => 'Bourse et job, loyer de colocation, courses, et le surplus sur un Livret A.',
                'thumb' => $thumbs['two-in'],
                'payload' => [
                    'horizon' => 36,
                    'nodes' => [
                        $node('r1', 'revenu', 'Bourse / APL', 40, 40, 550),
                        $node('r2', 'revenu', 'Job étudiant', 40, 200, 450),
                        $node('c1', 'compte', 'Compte courant', 360, 120),
                        $node('dloyer', 'depense', 'Loyer colocation', 720, 40),
                        $node('dcour', 'depense', 'Courses et resto', 720, 200),
                        $node('dtr', 'depense', 'Transports', 720, 360),
                        $node('la', 'livret', 'Livret A', 720, 520, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'dloyer', 'mode' => 'fixe', 'value' => 420],
                        ['from' => 'c1', 'to' => 'dcour', 'mode' => 'fixe', 'value' => 280],
                        ['from' => 'c1', 'to' => 'dtr', 'mode' => 'fixe', 'value' => 50],
                        ['from' => 'c1', 'to' => 'la', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'colocation' => [
                'title' => 'Colocation',
                'category' => 'Solo',
                'hint' => 'Salaire perso, quote-part du loyer et des charges, le reste vers l’épargne.',
                'thumb' => $thumbs['solo'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire', 40, 40, 2100),
                        $node('c1', 'compte', 'Compte perso', 360, 40),
                        $node('dloyer', 'depense', 'Quote-part loyer', 720, 40),
                        $node('dchg', 'depense', 'Charges coloc', 720, 200),
                        $node('dcour', 'depense', 'Quotidien perso', 720, 360),
                        $node('p1', 'repartiteur', 'Épargne', 720, 520),
                        $node('la', 'livret', 'Livret A', 1040, 440, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                        $node('ldds', 'livret', 'LDDS', 1040, 600, 0, ['rate' => 1.7, 'cap' => 12000, 'start' => 0, 'preset' => 'ldds']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'dloyer', 'mode' => 'fixe', 'value' => 550],
                        ['from' => 'c1', 'to' => 'dchg', 'mode' => 'fixe', 'value' => 80],
                        ['from' => 'c1', 'to' => 'dcour', 'mode' => 'fixe', 'value' => 700],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'la', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'p1', 'to' => 'ldds', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'retraite' => [
                'title' => 'Retraite',
                'category' => 'Solo',
                'hint' => 'Pension de base et complémentaire, charges du mois, surplus sur Livret A.',
                'thumb' => $thumbs['two-in'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Pension de base', 40, 40, 1400),
                        $node('r2', 'revenu', 'Complémentaire', 40, 200, 600),
                        $node('c1', 'compte', 'Compte courant', 360, 120),
                        $node('dloyer', 'depense', 'Loyer et charges', 720, 40),
                        $node('dcour', 'depense', 'Quotidien', 720, 200),
                        $node('dsante', 'depense', 'Santé', 720, 360),
                        $node('la', 'livret', 'Livret A', 720, 520, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 4000, 'preset' => 'livret-a']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'dloyer', 'mode' => 'fixe', 'value' => 780],
                        ['from' => 'c1', 'to' => 'dcour', 'mode' => 'fixe', 'value' => 650],
                        ['from' => 'c1', 'to' => 'dsante', 'mode' => 'fixe', 'value' => 80],
                        ['from' => 'c1', 'to' => 'la', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'couple' => [
                'title' => 'Couple, comptes séparés',
                'category' => 'Couple',
                'hint' => 'Deux salaires, un joint pour les factures, un joint pour le quotidien, épargne par personne.',
                'thumb' => $thumbs['two-in'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire A', 40, 40, 2400),
                        $node('r2', 'revenu', 'Salaire B', 40, 280, 2800),
                        $node('ca', 'compte', 'Compte A', 360, 40),
                        $node('cb', 'compte', 'Compte B', 360, 200),
                        $node('cf', 'compte', 'Joint Factures', 360, 360),
                        $node('cq', 'compte', 'Joint Quotidien', 360, 520),
                        $node('p1', 'repartiteur', 'Épargne', 360, 680),
                        $node('d1', 'depense', 'Prélèvements', 720, 360),
                        $node('d2', 'depense', 'Dépenses courantes', 720, 520),
                        $node('l1', 'livret', 'Livret A', 720, 40, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                        $node('l2', 'livret', 'LDDS', 720, 200, 0, ['rate' => 1.7, 'cap' => 12000, 'start' => 0, 'preset' => 'ldds']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'ca', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'cb', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'ca', 'to' => 'cf', 'mode' => 'fixe', 'value' => 900],
                        ['from' => 'ca', 'to' => 'cq', 'mode' => 'fixe', 'value' => 600],
                        ['from' => 'ca', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cb', 'to' => 'cf', 'mode' => 'fixe', 'value' => 1100],
                        ['from' => 'cb', 'to' => 'cq', 'mode' => 'fixe', 'value' => 800],
                        ['from' => 'cb', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cf', 'to' => 'd1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cq', 'to' => 'd2', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'l1', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'p1', 'to' => 'l2', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'couple-commun' => [
                'title' => 'Couple, tout en commun',
                'category' => 'Couple',
                'hint' => 'Deux salaires sur un seul joint, charges du foyer, puis LEP, Livret A et LDDS.',
                'thumb' => $thumbs['two-in'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire A', 40, 40, 2400),
                        $node('r2', 'revenu', 'Salaire B', 40, 200, 2200),
                        $node('c1', 'compte', 'Compte joint', 360, 120),
                        $node('d1', 'depense', 'Prélèvements', 720, 40),
                        $node('d2', 'depense', 'Quotidien', 720, 200),
                        $node('d3', 'depense', 'Impôts', 720, 360),
                        $node('p1', 'repartiteur', 'Épargne', 720, 520),
                        $node('lep', 'livret', 'LEP', 1040, 360, 0, ['rate' => 2.5, 'cap' => 10000, 'start' => 0, 'preset' => 'lep']),
                        $node('la', 'livret', 'Livret A', 1040, 520, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                        $node('ldds', 'livret', 'LDDS', 1040, 680, 0, ['rate' => 1.7, 'cap' => 12000, 'start' => 0, 'preset' => 'ldds']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'd1', 'mode' => 'fixe', 'value' => 1400],
                        ['from' => 'c1', 'to' => 'd2', 'mode' => 'fixe', 'value' => 1600],
                        ['from' => 'c1', 'to' => 'd3', 'mode' => 'fixe', 'value' => 300],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'lep', 'mode' => 'fixe', 'value' => 200],
                        ['from' => 'p1', 'to' => 'la', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'p1', 'to' => 'ldds', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'famille' => [
                'title' => 'Famille avec enfants',
                'category' => 'Famille',
                'hint' => 'Allocations, livrets des enfants, dépenses courantes, deux répartiteurs.',
                'thumb' => $thumbs['family'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire A', 40, 40, 2800),
                        $node('r2', 'revenu', 'Salaire B', 40, 200, 2200),
                        $node('r3', 'revenu', 'Allocations', 40, 360, 380),
                        $node('cf', 'compte', 'Joint Factures', 360, 40),
                        $node('cq', 'compte', 'Joint Quotidien', 360, 200),
                        $node('p1', 'repartiteur', 'Épargne foyer', 360, 360),
                        $node('p2', 'repartiteur', 'Livrets enfants', 360, 520),
                        $node('d1', 'depense', 'Prélèvements', 720, 40),
                        $node('d2', 'depense', 'Dépenses courantes', 720, 200),
                        $node('l1', 'livret', 'Livret A', 720, 360, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                        $node('l2', 'livret', 'LDDS', 720, 520, 0, ['rate' => 1.7, 'cap' => 12000, 'start' => 0, 'preset' => 'ldds']),
                        $node('le1', 'livret', 'Livret enfant 1', 720, 680, 0, ['rate' => 1.7, 'cap' => 1600, 'start' => 0, 'preset' => 'jeune']),
                        $node('le2', 'livret', 'Livret enfant 2', 720, 840, 0, ['rate' => 1.7, 'cap' => 1600, 'start' => 0, 'preset' => 'jeune']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'cf', 'mode' => 'fixe', 'value' => 1400],
                        ['from' => 'r1', 'to' => 'cq', 'mode' => 'fixe', 'value' => 800],
                        ['from' => 'r1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'cf', 'mode' => 'fixe', 'value' => 1000],
                        ['from' => 'r2', 'to' => 'cq', 'mode' => 'fixe', 'value' => 800],
                        ['from' => 'r2', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r3', 'to' => 'p2', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cf', 'to' => 'd1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cq', 'to' => 'd2', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'l1', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'p1', 'to' => 'l2', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p2', 'to' => 'le1', 'mode' => 'fixe', 'value' => 190],
                        ['from' => 'p2', 'to' => 'le2', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'monoparentale' => [
                'title' => 'Famille monoparentale',
                'category' => 'Famille',
                'hint' => 'Salaire, allocations et pension, loyer, quotidien, livret du foyer et livret enfant.',
                'thumb' => $thumbs['family'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire', 40, 40, 2200),
                        $node('r2', 'revenu', 'Allocations', 40, 200, 280),
                        $node('r3', 'revenu', 'Pension alimentaire', 40, 360, 350),
                        $node('c1', 'compte', 'Compte courant', 360, 200),
                        $node('dloyer', 'depense', 'Loyer', 720, 40),
                        $node('dcour', 'depense', 'Quotidien', 720, 200),
                        $node('dgarde', 'depense', 'Garde / extrascolaire', 720, 360),
                        $node('p1', 'repartiteur', 'Épargne', 720, 520),
                        $node('la', 'livret', 'Livret A', 1040, 440, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                        $node('le', 'livret', 'Livret enfant', 1040, 600, 0, ['rate' => 1.7, 'cap' => 1600, 'start' => 0, 'preset' => 'jeune']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r3', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'dloyer', 'mode' => 'fixe', 'value' => 850],
                        ['from' => 'c1', 'to' => 'dcour', 'mode' => 'fixe', 'value' => 900],
                        ['from' => 'c1', 'to' => 'dgarde', 'mode' => 'fixe', 'value' => 200],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'le', 'mode' => 'fixe', 'value' => 150],
                        ['from' => 'p1', 'to' => 'la', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'parents-etudiant' => [
                'title' => 'Parents + enfant étudiant',
                'category' => 'Famille',
                'hint' => 'Deux salaires, charges du foyer, aide loyer de l’enfant, épargne du foyer et livret jeune.',
                'thumb' => $thumbs['family'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire A', 40, 40, 2800),
                        $node('r2', 'revenu', 'Salaire B', 40, 200, 2400),
                        $node('c1', 'compte', 'Compte foyer', 360, 120),
                        $node('d1', 'depense', 'Prélèvements', 720, 40),
                        $node('d2', 'depense', 'Quotidien', 720, 200),
                        $node('daide', 'depense', 'Aide loyer enfant', 720, 360),
                        $node('p1', 'repartiteur', 'Épargne', 720, 520),
                        $node('la', 'livret', 'Livret A', 1040, 440, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                        $node('ldds', 'livret', 'LDDS', 1040, 600, 0, ['rate' => 1.7, 'cap' => 12000, 'start' => 0, 'preset' => 'ldds']),
                        $node('lj', 'livret', 'Livret jeune', 1040, 760, 0, ['rate' => 1.7, 'cap' => 1600, 'start' => 400, 'preset' => 'jeune']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'd1', 'mode' => 'fixe', 'value' => 1600],
                        ['from' => 'c1', 'to' => 'd2', 'mode' => 'fixe', 'value' => 1400],
                        ['from' => 'c1', 'to' => 'daide', 'mode' => 'fixe', 'value' => 450],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'lj', 'mode' => 'fixe', 'value' => 100],
                        ['from' => 'p1', 'to' => 'la', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'p1', 'to' => 'ldds', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'auto-entrepreneur' => [
                'title' => 'Auto-entrepreneur',
                'category' => 'Indépendant',
                'hint' => 'Chiffre d’affaires, provision URSSAF, rémunération vers le compte perso, épargne de précaution.',
                'thumb' => $thumbs['pro'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Chiffre d’affaires', 40, 200, 3500),
                        $node('cpro', 'compte', 'Compte professionnel', 360, 80),
                        $node('cperso', 'compte', 'Compte perso', 360, 360),
                        $node('p1', 'repartiteur', 'Épargne', 360, 560),
                        $node('dur', 'depense', 'Cotisations URSSAF', 720, 40),
                        $node('dchg', 'depense', 'Charges pro', 720, 200),
                        $node('dcour', 'depense', 'Dépenses courantes', 720, 360),
                        $node('l1', 'livret', 'Livret A', 720, 520, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                        $node('l2', 'livret', 'LDDS', 720, 680, 0, ['rate' => 1.7, 'cap' => 12000, 'start' => 0, 'preset' => 'ldds']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'cpro', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cpro', 'to' => 'dur', 'mode' => 'fixe', 'value' => 770],
                        ['from' => 'cpro', 'to' => 'dchg', 'mode' => 'fixe', 'value' => 200],
                        ['from' => 'cpro', 'to' => 'cperso', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cperso', 'to' => 'dcour', 'mode' => 'fixe', 'value' => 1600],
                        ['from' => 'cperso', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'l1', 'mode' => 'fixe', 'value' => 500],
                        ['from' => 'p1', 'to' => 'l2', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'salarie-freelance' => [
                'title' => 'Salarié + freelance',
                'category' => 'Indépendant',
                'hint' => 'Salaire stable d’un côté, chiffre d’affaires et URSSAF de l’autre, puis un seul foyer.',
                'thumb' => $thumbs['rental'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire', 40, 40, 2200),
                        $node('r2', 'revenu', 'CA freelance', 40, 280, 1800),
                        $node('cperso', 'compte', 'Compte perso', 360, 40),
                        $node('cpro', 'compte', 'Compte pro', 360, 280),
                        $node('dur', 'depense', 'Cotisations URSSAF', 720, 200),
                        $node('dchg', 'depense', 'Charges pro', 720, 360),
                        $node('dloyer', 'depense', 'Loyer', 720, 40),
                        $node('dcour', 'depense', 'Quotidien', 720, 520),
                        $node('p1', 'repartiteur', 'Épargne', 720, 680),
                        $node('la', 'livret', 'Livret A', 1040, 600, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                        $node('ldds', 'livret', 'LDDS', 1040, 760, 0, ['rate' => 1.7, 'cap' => 12000, 'start' => 0, 'preset' => 'ldds']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'cperso', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'cpro', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cpro', 'to' => 'dur', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'cpro', 'to' => 'dchg', 'mode' => 'fixe', 'value' => 80],
                        ['from' => 'cpro', 'to' => 'cperso', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cperso', 'to' => 'dloyer', 'mode' => 'fixe', 'value' => 800],
                        ['from' => 'cperso', 'to' => 'dcour', 'mode' => 'fixe', 'value' => 1600],
                        ['from' => 'cperso', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'la', 'mode' => 'fixe', 'value' => 500],
                        ['from' => 'p1', 'to' => 'ldds', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'locatif' => [
                'title' => 'Locatif + salaire',
                'category' => 'Indépendant',
                'hint' => 'Loyers perçus, charges du local, fiscalité provisionnée, surplus vers épargne longue.',
                'thumb' => $thumbs['rental'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire', 40, 40, 2600),
                        $node('r2', 'revenu', 'Loyers', 40, 280, 1400),
                        $node('cperso', 'compte', 'Compte perso', 360, 40),
                        $node('cloc', 'compte', 'Compte locatif', 360, 280),
                        $node('dcour', 'depense', 'Dépenses courantes', 720, 40),
                        $node('dchg', 'depense', 'Charges du local', 720, 200),
                        $node('dfisc', 'depense', 'Fiscalité locative', 720, 360),
                        $node('l1', 'livret', 'Livret A', 720, 520, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'cperso', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'cloc', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cloc', 'to' => 'dchg', 'mode' => 'fixe', 'value' => 350],
                        ['from' => 'cloc', 'to' => 'dfisc', 'mode' => 'fixe', 'value' => 280],
                        ['from' => 'cloc', 'to' => 'cperso', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cperso', 'to' => 'dcour', 'mode' => 'fixe', 'value' => 1800],
                        ['from' => 'cperso', 'to' => 'l1', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'tpe' => [
                'title' => 'TPE / gérant',
                'category' => 'Indépendant',
                'hint' => 'Chiffre d’affaires, charges d’exploitation, rémunération du gérant, réserve d’activité.',
                'thumb' => $thumbs['pro'],
                'payload' => [
                    'horizon' => 36,
                    'nodes' => [
                        $node('r1', 'revenu', 'Chiffre d’affaires', 40, 200, 8000),
                        $node('cpro', 'compte', 'Compte professionnel', 360, 200),
                        $node('cperso', 'compte', 'Compte perso', 720, 520),
                        $node('dach', 'depense', 'Achats et charges', 720, 40),
                        $node('dloc', 'depense', 'Loyer du local', 720, 200),
                        $node('dsoc', 'depense', 'Charges sociales', 720, 360),
                        $node('dcour', 'depense', 'Quotidien perso', 1040, 520),
                        $node('res', 'livret', 'Réserve activité', 1040, 200, 0, ['rate' => 0, 'cap' => 0, 'start' => 4000, 'preset' => 'custom', 'note' => 'Trésorerie de la structure, hors livret réglementé.']),
                        $node('la', 'livret', 'Livret A', 1040, 680, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'cpro', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cpro', 'to' => 'dach', 'mode' => 'fixe', 'value' => 2200],
                        ['from' => 'cpro', 'to' => 'dloc', 'mode' => 'fixe', 'value' => 900],
                        ['from' => 'cpro', 'to' => 'dsoc', 'mode' => 'fixe', 'value' => 1100],
                        ['from' => 'cpro', 'to' => 'cperso', 'mode' => 'fixe', 'value' => 2500],
                        ['from' => 'cpro', 'to' => 'res', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'cperso', 'to' => 'dcour', 'mode' => 'fixe', 'value' => 1600],
                        ['from' => 'cperso', 'to' => 'la', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'saisonnier' => [
                'title' => 'Revenu saisonnier',
                'category' => 'Indépendant',
                'hint' => 'Un mois moyen lissé, les charges du foyer, et une réserve pour tenir les mois bas.',
                'thumb' => $thumbs['save'],
                'payload' => [
                    'horizon' => 24,
                    'nodes' => [
                        $node('r1', 'revenu', 'Revenu moyen lissé', 40, 160, 2800),
                        $node('c1', 'compte', 'Compte courant', 360, 160),
                        $node('dchg', 'depense', 'Charges du mois', 720, 40),
                        $node('dcour', 'depense', 'Quotidien', 720, 200),
                        $node('p1', 'repartiteur', 'Après charges', 720, 360),
                        $node('res', 'livret', 'Réserve mois bas', 1040, 280, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 2500, 'preset' => 'livret-a', 'note' => 'À piocher les mois sans rentrée. Ajustez le revenu moyen.']),
                        $node('ldds', 'livret', 'LDDS', 1040, 440, 0, ['rate' => 1.7, 'cap' => 12000, 'start' => 0, 'preset' => 'ldds']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'dchg', 'mode' => 'fixe', 'value' => 1600],
                        ['from' => 'c1', 'to' => 'dcour', 'mode' => 'fixe', 'value' => 700],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'res', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'p1', 'to' => 'ldds', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'precaution' => [
                'title' => 'Épargne de précaution',
                'category' => 'Épargne',
                'hint' => 'Un seul revenu, une règle de trois mois de charges, saturation du LEP puis du Livret A.',
                'thumb' => $thumbs['save'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire', 40, 200, 2200),
                        $node('c1', 'compte', 'Compte courant', 360, 200),
                        $node('d1', 'depense', 'Charges du mois', 720, 80),
                        $node('p1', 'repartiteur', 'Précaution', 720, 280),
                        $node('lep', 'livret', 'LEP', 1040, 200, 0, ['rate' => 2.5, 'cap' => 10000, 'start' => 0, 'preset' => 'lep']),
                        $node('la', 'livret', 'Livret A', 1040, 400, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'd1', 'mode' => 'fixe', 'value' => 1800],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'lep', 'mode' => 'fixe', 'value' => 300],
                        ['from' => 'p1', 'to' => 'la', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'apport' => [
                'title' => 'Objectif apport',
                'category' => 'Épargne',
                'hint' => 'Tout ce qui n’est pas dépensé va vers l’apport ; repartio affiche la date d’atteinte du montant cible.',
                'thumb' => $thumbs['goal'],
                'payload' => [
                    'horizon' => 60,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire A', 40, 40, 2200),
                        $node('r2', 'revenu', 'Salaire B', 40, 280, 2400),
                        $node('c1', 'compte', 'Compte joint', 360, 160),
                        $node('d1', 'depense', 'Loyer', 720, 40),
                        $node('d2', 'depense', 'Quotidien', 720, 200),
                        $node('d3', 'depense', 'Impôts', 720, 360),
                        $node('p1', 'repartiteur', 'Tout le reste', 720, 520),
                        $node('lep', 'livret', 'LEP', 1040, 360, 0, ['rate' => 2.5, 'cap' => 10000, 'start' => 0, 'preset' => 'lep']),
                        $node('la', 'livret', 'Livret A', 1040, 520, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                        $node('lap', 'livret', 'Livret apport', 1040, 680, 0, ['rate' => 1.7, 'cap' => 0, 'start' => 0, 'preset' => 'custom', 'note' => 'Cible d’apport : ajustez le versement et lisez la projection.']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'd1', 'mode' => 'fixe', 'value' => 1200],
                        ['from' => 'c1', 'to' => 'd2', 'mode' => 'fixe', 'value' => 1600],
                        ['from' => 'c1', 'to' => 'd3', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'lep', 'mode' => 'fixe', 'value' => 200],
                        ['from' => 'p1', 'to' => 'la', 'mode' => 'fixe', 'value' => 300],
                        ['from' => 'p1', 'to' => 'lap', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'projet' => [
                'title' => 'Projet à date',
                'category' => 'Épargne',
                'hint' => 'Vacances, permis ou voyage : une enveloppe dédiée, le reste sur Livret A.',
                'thumb' => $thumbs['save'],
                'payload' => [
                    'horizon' => 18,
                    'nodes' => [
                        $node('r1', 'revenu', 'Salaire', 40, 160, 2300),
                        $node('c1', 'compte', 'Compte courant', 360, 160),
                        $node('d1', 'depense', 'Charges du mois', 720, 40),
                        $node('p1', 'repartiteur', 'Après charges', 720, 240),
                        $node('proj', 'livret', 'Enveloppe projet', 1040, 160, 0, ['rate' => 1.7, 'cap' => 0, 'start' => 800, 'preset' => 'custom', 'note' => 'Permis, vacances, voyage : changez le titre et le versement.']),
                        $node('la', 'livret', 'Livret A', 1040, 360, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 0, 'preset' => 'livret-a']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'd1', 'mode' => 'fixe', 'value' => 1700],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'proj', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'p1', 'to' => 'la', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'association' => [
                'title' => 'Association',
                'category' => 'Collectif',
                'hint' => 'Cotisations et subvention lissées sur le mois, local, actions, fonds de réserve.',
                'thumb' => $thumbs['two-in'],
                'payload' => [
                    'horizon' => 12,
                    'nodes' => [
                        $node('r1', 'revenu', 'Cotisations', 40, 40, 1800),
                        $node('r2', 'revenu', 'Subvention', 40, 200, 400),
                        $node('c1', 'compte', 'Compte association', 360, 120),
                        $node('dloc', 'depense', 'Local et assurances', 720, 40),
                        $node('dact', 'depense', 'Actions / événements', 720, 200),
                        $node('dadm', 'depense', 'Frais de fonctionnement', 720, 360),
                        $node('res', 'livret', 'Fonds de réserve', 720, 520, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 1200, 'preset' => 'livret-a', 'note' => 'Réserve pour un mauvais trimestre ou un imprévu.']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'dloc', 'mode' => 'fixe', 'value' => 450],
                        ['from' => 'c1', 'to' => 'dact', 'mode' => 'fixe', 'value' => 800],
                        ['from' => 'c1', 'to' => 'dadm', 'mode' => 'fixe', 'value' => 80],
                        ['from' => 'c1', 'to' => 'res', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
            'club' => [
                'title' => 'Club sportif',
                'category' => 'Collectif',
                'hint' => 'Cotisations et sponsors, licences, équipements, déplacements, caisse du club.',
                'thumb' => $thumbs['family'],
                'payload' => [
                    'horizon' => 12,
                    'nodes' => [
                        $node('r1', 'revenu', 'Cotisations', 40, 40, 2400),
                        $node('r2', 'revenu', 'Sponsors / subvention', 40, 200, 600),
                        $node('c1', 'compte', 'Compte du club', 360, 120),
                        $node('dlic', 'depense', 'Licences / affiliation', 720, 40),
                        $node('dequ', 'depense', 'Équipements', 720, 200),
                        $node('ddep', 'depense', 'Déplacements', 720, 360),
                        $node('dsalle', 'depense', 'Terrain / salle', 720, 520),
                        $node('p1', 'repartiteur', 'Caisse', 720, 680),
                        $node('res', 'livret', 'Réserve du club', 1040, 600, 0, ['rate' => 1.7, 'cap' => 22950, 'start' => 800, 'preset' => 'livret-a']),
                        $node('proj', 'livret', 'Enveloppe tournoi', 1040, 760, 0, ['rate' => 0, 'cap' => 0, 'start' => 0, 'preset' => 'custom', 'note' => 'Déplacement ou inscription à mettre de côté.']),
                    ],
                    'edges' => [
                        ['from' => 'r1', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'r2', 'to' => 'c1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'c1', 'to' => 'dlic', 'mode' => 'fixe', 'value' => 500],
                        ['from' => 'c1', 'to' => 'dequ', 'mode' => 'fixe', 'value' => 400],
                        ['from' => 'c1', 'to' => 'ddep', 'mode' => 'fixe', 'value' => 700],
                        ['from' => 'c1', 'to' => 'dsalle', 'mode' => 'fixe', 'value' => 450],
                        ['from' => 'c1', 'to' => 'p1', 'mode' => 'reste', 'value' => 0],
                        ['from' => 'p1', 'to' => 'proj', 'mode' => 'fixe', 'value' => 200],
                        ['from' => 'p1', 'to' => 'res', 'mode' => 'reste', 'value' => 0],
                    ],
                ],
            ],
        ];
    }
}
